image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public # ✅ 確保這行存在，把 dist 改名為 public
  artifacts:
    paths:
      - public # ✅ 這樣 GitLab Pages 才會讀取 public 資料夾

pages: # ✅ 這一段非常重要，讓 GitLab 正確部署 Pages
  stage: deploy
  script:
    - mv public /public
  artifacts:
    paths:
      - public
  only:
    - main
