image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - pages

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist/* public
    - ls public  # 確保 public 目錄內有 index.html
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: pages
  script:
    - echo "Deploying to GitLab Pages..."
    - ls public 
  artifacts:
    paths:
      - public
  only:
    - main
