image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - ls -al dist  # ✅ 確認 `dist/` 是否有生成
    - mv dist public  # ✅ 確保 `dist/` 被正確移動到 `public/`
    - ls -al public  # ✅ 再次確認 `public/` 內部是否有檔案
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mv public /public
  artifacts:
    paths:
      - public
  only:
    - main
