image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public  # 確保 GitLab Pages 可以找到 public/
  artifacts:
    paths:
      - public  # 確保 artifacts 內有 public/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public  # GitLab Pages 需要的 public/ 目錄
  only:
    - main
