image: node:18 # 使用 Node.js 18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public # 把 dist 改名為 public，讓 GitLab Pages 讀取
  artifacts:
    paths:
      - public # GitLab Pages 需要這個資料夾
  only:
    - main # 只在 main 分支執行
