image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - ls -al dist  # 確認 dist/ 是否有內容
    - mv dist public  # 把 dist/ 改名為 public/
    - ls -al public  # 確認 public/ 內部是否有檔案
  artifacts:
    paths:
      - public  # 確保 GitLab Pages 可以找到 public/
    expire_in: 1 week  # 設定 artifacts 的保存時間

pages:
  stage: deploy
  script:
    - echo "Deploying GitLab Pages..."  # 移除 `mv public /public`
  artifacts:
    paths:
      - public
  only:
    - main
